# Week 2

## Linear Algebra Functions in Python

In [3]:
import numpy as np
#np.linspace: Return evenly spaced numbers over a specified interval.
#np.reshape: Gives a new shape to an array without changing its data.
#np.random.randint: duh
import random

In [23]:
#Given the following matricies and vectors
M = np.linspace(-8, 8, 9).reshape(3,3)
N = np.random.randint(-8, 8, size=(3,3))
O = 2 * N

v1 = np.array([1,3,5,7])
v2 = np.array([2,4,6,8])
v3 = np.array([-2, 5, 1, 3])


print(v1, v2, v3)
print("M")
print(M) 
print("N")
print(N)
print("O")
print(O)

[1 3 5 7] [2 4 6 8] [-2  5  1  3]
M
[[-8. -6. -4.]
 [-2.  0.  2.]
 [ 4.  6.  8.]]
N
[[-1 -6 -7]
 [ 6 -3  6]
 [ 5  4  5]]
O
[[ -2 -12 -14]
 [ 12  -6  12]
 [ 10   8  10]]


In [25]:
print("N.dot(M)")
print(N.dot(M))
print("M.dot(N)")
print(M.dot(N))
print("v1.dot(v2)")
print(v1.dot(v2))

N.dot(M)
[[ -8. -36. -64.]
 [-18.   0.  18.]
 [-28.   0.  28.]]
M.dot(N)
[[-48.  50.   0.]
 [ 12.  20.  24.]
 [ 72. -10.  48.]]
v1.dot(v2)
100


### The multi_dot() function returns the product of two or several matrices

In [28]:
np.linalg.multi_dot([M, N, O])

array([[ 696.,  276., 1272.],
       [ 456.,  -72.,  312.],
       [ 216., -420., -648.]])

### The vdot() function returns the priduct of two vectors. 
#### It does not perform a matrix multiplication. It should only be used for vectors 

In [29]:
np.vdot(v1,v2)

100

In [30]:
# inner() fuction returns the inner product of two arrays
np.inner(v3,v1)

39

In [31]:
# The matmul()function returns the product of two matricies
np.matmul(M,N)

array([[-48.,  50.,   0.],
       [ 12.,  20.,  24.],
       [ 72., -10.,  48.]])

In [32]:
#linalg.matrix_power(M,n) raides the square matrix M to power of n.
np.linalg.matrix_power(M,3)

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

In [40]:
# linalg.eig(O) returns both the eigenvalues and eigenvectors of the matrix O

print("O")
print(O)
print(np.linalg.eig(O))
eig_vals, eig_vects = np.linalg.eig(O)
print("vals")
print(eig_vals)
print("vectors")
print(eig_vects)

O
[[ -2 -12 -14]
 [ 12  -6  12]
 [ 10   8  10]]
(array([ 5.37363905+13.60637474j,  5.37363905-13.60637474j,
       -8.74727809 +0.j        ]), array([[-0.74977528+0.j        , -0.74977528-0.j        ,
        -0.33450906+0.j        ],
       [ 0.04087321+0.37804444j,  0.04087321-0.37804444j,
        -0.7891162 +0.j        ],
       [ 0.35986384+0.40465643j,  0.35986384-0.40465643j,
         0.5151692 +0.j        ]]))
vals
[ 5.37363905+13.60637474j  5.37363905-13.60637474j
 -8.74727809 +0.j        ]
vectors
[[-0.74977528+0.j         -0.74977528-0.j         -0.33450906+0.j        ]
 [ 0.04087321+0.37804444j  0.04087321-0.37804444j -0.7891162 +0.j        ]
 [ 0.35986384+0.40465643j  0.35986384-0.40465643j  0.5151692 +0.j        ]]


In [41]:
# linalg.det(N) returns the determinate of the matrix N
print("N")
print(N)
print("np.linalg.det(N)")
np.linalg.det(N)

N
[[-1 -6 -7]
 [ 6 -3  6]
 [ 5  4  5]]
np.linalg.det(N)


-234.00000000000006

In [42]:
# np.linalg.inv(N) returns the inverse of the matrix N
print("np.linalg.inv(N)")
print(np.linalg.inv(N))

np.linalg.inv(N)
[[ 0.16666667 -0.00854701  0.24358974]
 [-0.         -0.12820513  0.15384615]
 [-0.16666667  0.11111111 -0.16666667]]


## Using Matrices in Python

In [45]:
L = np.linspace(0,120,25)
print(L)

[  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.
  70.  75.  80.  85.  90.  95. 100. 105. 110. 115. 120.]


In [46]:
M = L.reshape(5,5)
print(M)

[[  0.   5.  10.  15.  20.]
 [ 25.  30.  35.  40.  45.]
 [ 50.  55.  60.  65.  70.]
 [ 75.  80.  85.  90.  95.]
 [100. 105. 110. 115. 120.]]


very important: The dimension that you would choose, the product of those dimensions should be exactly equal to the number of elements that you have

In [49]:
#Filling a matrix with radom intigers
R = np.random.randint(-5, 4, size=(4,4))
print(R)

[[-1  1 -2 -1]
 [-3  2  0 -5]
 [ 1 -3 -2  0]
 [ 2 -1 -3 -3]]


### Selecting Specific Entry of a Matrix

In [50]:
#Index starts at 0,1,2,3
print("M")
print(M)
print("First Row")
print(M[0])
print("Last Row")
print(M[-1])

M
[[  0.   5.  10.  15.  20.]
 [ 25.  30.  35.  40.  45.]
 [ 50.  55.  60.  65.  70.]
 [ 75.  80.  85.  90.  95.]
 [100. 105. 110. 115. 120.]]
First Row
[ 0.  5. 10. 15. 20.]
Last Row
[100. 105. 110. 115. 120.]


In [53]:
print("First Column")
print(M[:,0])
print("Grab only the first four values")
print(M[0:4,0])
print("Slice and dice as you like")
print(M[0:3,1:4])

First Column
[  0.  25.  50.  75. 100.]
Grab only the first four values
[ 0. 25. 50. 75.]
Slice and dice as you like
[[ 5. 10. 15.]
 [30. 35. 40.]
 [55. 60. 65.]]


## Solving Linear Equations Using Python

In [59]:
from IPython import display
#from IPython.display.Latex import Latex
import sympy as sy

Given the following system of linear equations (I):
$$
4x + 3y + 2x = 25 \\
-2x + 2y + 3z = -10\\
3x - 5y + 2z = -4\\
$$

### Solve using Inverse Method

In [64]:
M = np.array([[4,3,2],[-2,2,3],[3,-5,2]]) #coefficients matrix
K = np.array([[25],[-10],[-4]])
print(M); print(K)
V = np.linalg.inv(M).dot(K)
print("V")
print(V)

[[ 4  3  2]
 [-2  2  3]
 [ 3 -5  2]]
[[ 25]
 [-10]
 [ -4]]
V
[[ 5.]
 [ 3.]
 [-2.]]


### Solve using Reduced Row Echelon Form

In [67]:
from sympy import *
A = Matrix([[4,3,2,25],[-2,2,3,-10],[3,-5,2,-4]]) #Augmented Matrix
A

Matrix([
[ 4,  3, 2,  25],
[-2,  2, 3, -10],
[ 3, -5, 2,  -4]])

In [70]:
A.rref(pivots=False)

Matrix([
[1, 0, 0,  5],
[0, 1, 0,  3],
[0, 0, 1, -2]])

### linalg.solve() method

In [74]:
Sol = np.linalg.solve(M,K)
print(Sol)
?print

[[ 5.]
 [ 3.]
 [-2.]]


Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method
